#!/bin/sh
# brew.sh — generate the Homebrew formula for a released version.
#
#   scripts/brew.sh formula <version> <sha256sums-file>   print the formula
#   scripts/brew.sh platforms                             the four it covers
#
# The formula is generated, not committed, for the same reason ROADMAP.md is
# generated: every `sha256` line in it is a fact about a file that does not
# exist yet when a human would be writing the formula. A checksum somebody
# typed is a checksum that is wrong the first time an archive is rebuilt, and
# Homebrew's failure for that is a download that aborts on a mismatch — which
# reads like a network problem.
#
# The release workflow runs this over the SHA256SUMS it just produced and
# attaches the result to the release, so
#
#   brew install https://github.com/Allan-Nava/edgemix/releases/download/vX.Y.Z/edgemix.rb
#
# works with no tap at all. Copying that same file into a homebrew-edgemix tap
# is then a copy, not a rewrite.
#
# edgemix cannot go into homebrew-core: the licence is PolyForm Noncommercial
# and core only takes open-source ones. That is a licensing fact, not an
# oversight, and it is why the install instructions name a URL or a tap.
#
# POSIX sh and awk only, like the rest of scripts/.

set -eu

repo="Allan-Nava/edgemix"
homepage="https://allan-nava.github.io/edgemix/"
desc="Read a production access log: the mix, the peak second, and where it waited"
license="PolyForm-Noncommercial-1.0.0"

# The platforms a formula can install. Homebrew runs on macOS and on Linux, and
# on both architectures; Windows is in the release but not here.
platforms='darwin_arm64
darwin_amd64
linux_arm64
linux_amd64'

usage() {
	echo "usage: scripts/brew.sh formula <version> <sha256sums-file>" >&2
	echo "       scripts/brew.sh platforms" >&2
	exit 2
}

# sha_for prints the sha256 of one archive from a sha256sum-format file.
# A missing entry is fatal and says which one: a formula with a blank checksum
# would be accepted by this script and rejected by every user.
sha_for() {
	sums=$1
	name=$2
	awk -v want="$name" '
		{
			# `<sha>  <name>`, and the name may carry a directory prefix.
			n = $2
			sub(/^.*\//, "", n)
			if (n == want) { print $1; found = 1; exit }
		}
		END { if (!found) exit 1 }
	' "$sums" || {
		echo "brew.sh: $sums has no checksum for $name" >&2
		exit 1
	}
}

formula() {
	version=$1
	sums=$2
	[ -f "$sums" ] || {
		echo "brew.sh: no such checksum file: $sums" >&2
		exit 1
	}
	case "$version" in
	v*)
		echo "brew.sh: pass the version without the leading v (got $version): it is what the binary reports and what the formula's test asserts" >&2
		exit 1
		;;
	esac

	# Read every checksum first, so a missing one fails before half a formula has
	# been printed to stdout and redirected into a file.
	#
	# Four explicit lines rather than a loop over $platforms and an eval: a
	# Homebrew formula has four hand-shaped `on_macos`/`on_linux` blocks, not a
	# loop, so pretending the data drives it hid the assignments from the reader
	# and from shellcheck both. brew_test.sh asserts that every platform the
	# list names does appear in the formula, which is the check the loop was
	# standing in for.
	sha_darwin_arm64=$(sha_for "$sums" "edgemix_${version}_darwin_arm64.tar.gz")
	sha_darwin_amd64=$(sha_for "$sums" "edgemix_${version}_darwin_amd64.tar.gz")
	sha_linux_arm64=$(sha_for "$sums" "edgemix_${version}_linux_arm64.tar.gz")
	sha_linux_amd64=$(sha_for "$sums" "edgemix_${version}_linux_amd64.tar.gz")

	url() { printf 'https://github.com/%s/releases/download/v%s/edgemix_%s_%s.tar.gz' "$repo" "$version" "$version" "$1"; }

	cat <<RUBY
# Generated by scripts/brew.sh for edgemix $version — do not edit by hand.
#
# Install without a tap:
#   brew install https://github.com/$repo/releases/download/v$version/edgemix.rb
#
# The checksums below come from the release run that built the archives, not
# from a human. edgemix reads files and makes no network calls, so nothing here
# needs a service, a token or a daemon.
class Edgemix < Formula
  desc "$desc"
  homepage "$homepage"
  version "$version"
  license "$license"

  on_macos do
    on_arm do
      url "$(url darwin_arm64)"
      sha256 "$sha_darwin_arm64"
    end
    on_intel do
      url "$(url darwin_amd64)"
      sha256 "$sha_darwin_amd64"
    end
  end

  on_linux do
    on_arm do
      url "$(url linux_arm64)"
      sha256 "$sha_linux_arm64"
    end
    on_intel do
      url "$(url linux_amd64)"
      sha256 "$sha_linux_amd64"
    end
  end

  def install
    bin.install "edgemix"
    doc.install "README.md", "CHANGELOG.md", "LICENSE"
  end

  test do
    # The archives stamp the version with no leading v, which is what makes this
    # assertion possible at all: it checks that the binary in the bottle is the
    # one this formula claims, not merely that something ran.
    assert_match "edgemix #{version}", shell_output("#{bin}/edgemix version")

    # And one real measurement, from a log written here: two requests in the
    # same second, so the report has to say the peak was 2 req/s and not 1.
    (testpath/"edge.log").write <<~LOG
      10.0.0.9:1 [19/Aug/2026:18:06:38.001] fe be/s1 0/0/0/12/13 200 100 - - ---- 1/1/0/0/0 0/0 "GET / HTTP/1.1"
      10.0.0.9:2 [19/Aug/2026:18:06:38.900] fe be/s1 0/0/0/15/16 200 100 - - ---- 1/1/0/0/0 0/0 "GET /a.js HTTP/1.1"
    LOG
    assert_match "peak 2 req/s", shell_output("#{bin}/edgemix analyze #{testpath}/edge.log")
  end
end
RUBY
}

case "${1:-}" in
formula)
	[ $# -eq 3 ] || usage
	formula "$2" "$3"
	;;
platforms)
	printf '%s\n' "$platforms"
	;;
*)
	usage
	;;
esac
